### PR TITLE
Added custom background color

### PR DESCRIPTION
**Pull request by alanmesquita**
Sometimes we need to use custom colors like truecolors, or just for fun. I want to change Matchmaker background color in vim configs.
I would like to suggest this change, what do you think? Please review and give me the feedback.

### CODE REVIEW

**Comment by mvoto** [comment]
I have tried this suggested color on highlight line with truecolors and looks much better than the white one.
This can be a simple but significant change :+1:

**Comment by tommcdo** [comment]
This can already be done by overriding the `Matchmaker` highlight group, which offers more customization than just the GUI background color. This is documented under `:help matchmaker-highlight`.

**Comment by qstrahl** [comment]
@alanmesquita @mvoto Your thoughts on what @tommcdo said? I'm inclined to close this PR but want to hear from you first.

**Comment by alanmesquita** [comment]
I understood @tommcdo,  usually in the vim plugin I do something like `g: something = 1` and I thought it would be simpler to have it too. Thanks a lot for the feedback, this plugin though simple is very useful to me. Yes, I understand @qstrahl, thanks for the feedback.

**Comment by qstrahl** [comment]
All right, I'll close this then

**Pull request closed without merging**
