### PR TITLE
Fix markdown formatting for Readme

### PR DESCRIPTION
**Pull request by mvoto**
This adds simple spaces to have a proper formatting on Readme file.
Please let me know if this is a relevant change.

### CODE REVIEW

**Comment by qstrahl** [comment]
Oh... whoops. Thanks for the fix! :D

**Comment by mvoto** [comment]
@qstrahl sorry for my lack of knowledge, but how should we proceed to send that `develop` changes to the `master` branch ?

**Comment by qstrahl** [comment]
@mvoto I'm on it. c:

**Comment by mvoto** [comment]
Okay @qstrahl thanks !

**Pull request merged**
